module : bone_segmentation2d.BoneSegmentation
model: unet_2d.UNet2D
datamodule : subject_split.SubjectSplit
dataset : frame_paired.FramePaired
data_root : ./data/train
output_path : ./results
num_workers : 0
batch_size : 2
log_every_n_steps : 10
learning_rate : 0.0002
min_epochs : 1
max_epochs : 10
in_channels : 1
out_channels: 1
use_positive_weights: False
load_size: 256
crop_size: 256
test_subjects: "spine10"
random_split: "80_20"
gpus: 0
project_name: 'bone-segmentation'
group_name: 'unet'
